# ВАЖНО: замени имя приложения на уникальное перед деплоем!
app = "CHANGE_ME_APP_NAME"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/bank.sqlite"
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
